V5
subsquid/hydra pull request #141
Opened 2021-11-04 05:22 UTC by rightjelkin

New cli commands:
- deployment upgrade (creates a new version of deployment by deployment name)
- deployment destroy (destroy given deployment version by deployment and version names)
- deployment version list (returns list of deployment versions by name)
Updated:
- deployment list (new field from versioning logic)

2021-11-04 05:28 UTC, rightjelkin commented
Forgot about unit-tests fixing according on new API

2021-11-04 19:53 UTC, dzhelezov commented on packages/hydra-cli/src/commands/deploy.ts
> +      }
Let's always show an info line: `Releasing the Squid at ${remoteUrl}` before the actual deployment starts

2021-11-05 05:59 UTC, eldargab requested changes
Apart from inline comments, command names are clearly ugly.

My suggestion would be:

```
app:deploy
app:delete
app:switch
app:ls
```

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deployment-versions/ls.ts
> +    'no-truncate': flags.boolean({
If it is true by default, it should be named `truncate` a be false by default.

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deployments/ls.ts
> +    'no-truncate': flags.boolean({
Should be just `truncate`

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deployment-versions/ls.ts
> +    'deployment-name': flags.string({
There should be just a one command for listing of all deployments. For deployment identification it should output 2 columns: app name and version. To output versions of just a one app, optional flag can be used.

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/upgrade.ts
> +      throw Error(`Remote url with name ${remoteUrlName} not exists`)
rude

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deploy.ts
> +    const remoteNumber = await cli.prompt(
May be use library like https://github.com/cyrilwanner/cli-select

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deploy.ts
> +    const diffs = await git.diffSummary([
This is incorrect. First of all, remote can be stale and we can get false equality. Second, there is no need for such a clever check here. Branches are equal, when their commit hashes are equal.

2021-11-05 05:59 UTC, eldargab commented on packages/hydra-cli/src/commands/deploy.ts
> +        return
Exit code should be non-zero

2021-11-05 06:13 UTC, eldargab commented
May be we can define the target remote branch as an upstream of a current local branch?

2021-11-21 16:18 UTC, merged