deployment logs & more obvious deploying flow
subsquid/hydra pull request #149
Opened 2021-12-01 08:42 UTC by rightjelkin

2021-12-02 10:27 UTC, eldargab requested changes

2021-12-02 10:27 UTC, eldargab commented on packages/hydra-cli/src/commands/app/deploy.ts
> +      `${remoteUrl.refs.fetch}.git#${remoteCommit.latest?.hash}`
This can potentially yield `remote#undefined`

2021-12-02 10:27 UTC, eldargab commented on packages/hydra-cli/src/commands/app/deploy.ts
> +            cli.action.start('◷ Preparing your squid')
Looks a bit strange first to update the process status as everything goes fine and immediately fail afterwards.

2021-12-02 10:27 UTC, eldargab commented on packages/hydra-cli/src/rest-client/routes/deploy.ts
>    const apiUrl = `${baseUrl}/client/project/${name}/version`
By now, this request cooking stuff is duplicated quite a bit across CLI. Would be nice to move it into a separate module. No rush on this.

2021-12-02 10:27 UTC, eldargab commented on packages/hydra-cli/src/rest-client/routes/log.ts
> +      process.stdout.write(dataString)
I am wondering, could small writes here be delayed indefinitely?

2021-12-02 11:52 UTC, rightjelkin commented on packages/hydra-cli/src/commands/app/deploy.ts
> +      `${remoteUrl.refs.fetch}.git#${remoteCommit.latest?.hash}`
It can happen only if we got no any remote, but this case checks higher. We should just remove this optional chaining operator...it was added during manual testing cuz of eslint (when commenting some error handlers)

2021-12-02 11:57 UTC, rightjelkin commented on packages/hydra-cli/src/commands/app/deploy.ts
> +            cli.action.start('◷ Preparing your squid')
May be we should take away error checking for concrete case statement. But for other I think this is normal, because of, for ex., building process here contains building two images and one of them can be failed for different reasons (same as push)

2021-12-02 12:00 UTC, rightjelkin commented on packages/hydra-cli/src/rest-client/routes/log.ts
> +      process.stdout.write(dataString)
I do not fully understand, delayed by kube? Or could we delay them for some reasons?

2021-12-02 14:38 UTC, eldargab commented on packages/hydra-cli/src/rest-client/routes/log.ts
> +      process.stdout.write(dataString)
I was worried about that stdout might be buffered, but never mind, it seems to work.

>delayed by kube?

Yes, this is another concern, again because of buffering. Api server might write a small message to the socket and it will stuck in the buffer until further writes.

2021-12-02 14:41 UTC, eldargab requested changes

2021-12-02 14:41 UTC, eldargab commented on packages/hydra-cli/src/commands/app/deploy.ts
> +      `${remoteUrl.refs.fetch}.git#${remoteCommit.latest?.hash}`
Yes, please remove! Or if the type checker complains, assert it is non-null explicitly.

2021-12-03 07:33 UTC, rightjelkin commented
3a2fad0 also contains url parameter for deploying a squid without repo cloning

2021-12-06 12:08 UTC, eldargab approved these changes

2021-12-06 12:08 UTC, merged